=== pan-narrans/DAW/Marcas/XML/Práctica 01 - xml básico/desayuno.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- definition of simple elements -->
  <xs:element name="nombre" type="xs:string" />
  <xs:element name="precio" type="xs:float" />
  <xs:element name="descripcion" type="xs:string" />
  <xs:element name="calorias" type="xs:string" />


  <!-- definition of complex elements -->
  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre" />
        <xs:element ref="precio" />
        <xs:element ref="descripcion" />
        <xs:element ref="calorias" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="menu">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="item" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>


</xs:schema>

=== pan-narrans/DAW/Marcas/XML/Práctica 01 - xml básico/desayuno.xml
<?xml version="1.0" encoding="UTF-8"?>

<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="desayuno.xsd">
  <item>
    <nombre>Gofres Belgas</nombre>
    <precio>5.95</precio>
    <descripcion>Dos de nuestros famosos Gofres belgas con abundante sirope</descripcion>
    <calorias>650</calorias>
  </item>

  <item>
    <nombre>Gofres Belgas con Fresas</nombre>
    <precio>7.95</precio>
    <descripcion>Ligeros gofres belgas cubiertos de fresas y nata montada</descripcion>
    <calorias>900</calorias>
  </item>

  <item>
    <nombre>Gofres Belgas con frutas del bosque</nombre>
    <precio>8.95</precio>
    <descripcion>Ligeros gofres belgas cubiertos con frutas del bosque y nata montada</descripcion>
    <calorias>900</calorias>
  </item>

  <item>
    <nombre>Tostada Francesa</nombre>
    <precio>4.50</precio>
    <descripcion>Dos gruesas rebanadas de nuestro pan franc√©s casero</descripcion>
    <calorias>600</calorias>
  </item>

  <item>
    <nombre>Desayuno de la casa </nombre>
    <precio>6.95</precio>
    <descripcion>Dos huevos, bacon o salchicha, tostada y patatas fritas </descripcion>
    <calorias>950</calorias>
  </item>

</menu>
