=== pan-narrans/DAW/Marcas/XML/Práctica 01 - xml básico/mensaje.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- simple-->
  <xs:element name="nombre" type="xs:string" />
  <xs:element name="email" type="xs:string" />
  <xs:element name="asunto" type="xs:string" />
  <xs:element name="parrafo" type="xs:string" />

  <!-- complex-->
  <xs:element name="remite">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre" />
        <xs:element ref="email" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="destinatario">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre" />
        <xs:element ref="email" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="texto">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="parrafo" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="mensaje">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="remite" />
        <xs:element ref="destinatario" />
        <xs:element ref="asunto" />
        <xs:element ref="texto" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== pan-narrans/DAW/Marcas/XML/Práctica 01 - xml básico/mensaje.xml
<?xml version="1.0" encoding="UTF-8"?>

<mensaje xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="mensaje.xsd" >
  <remite>
    <nombre>Alfredo Reino</nombre>
    <email>alf@bium.com</email>
  </remite>
  <destinatario>
    <nombre>Bill Clinton</nombre>
    <email>president@whitehouse.gov</email>
  </destinatario>
  <asunto>Hola Bill</asunto>
  <texto>
    <parrafo>Â¿Hola que tal?</parrafo>
    <parrafo>Hace mucho tiempo que no escribes. A ver si llamas y quedamos pronto</parrafo>
    <parrafo>Un saludo.</parrafo>
  </texto>
</mensaje>
