=== pan-narrans/DAW/Marcas/XML/Práctica Exámen/cocina.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <xs:element name="cocina">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="sopas"/>
        <xs:element ref="postres"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="sopas">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="sopa" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="sopa">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ingredientes"/>
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required"/>
      <xs:attribute name="precio" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="ingredientes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ingrediente" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="postres">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="titulo" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="titulo">
    <xs:complexType mixed="true">
      <xs:attribute name="precio" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== pan-narrans/DAW/Marcas/XML/Práctica Exámen/cocina.xml
<?xml version="1.0" encoding="UTF-8"?>
<cocina xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="cocina.xsd">
  <sopas>
    <sopa nombre="Juliana" precio="15€">
      <ingredientes>
        <ingrediente>Espárragos</ingrediente>
        <ingrediente>Cebolla</ingrediente>
        <ingrediente>Calabacín</ingrediente>
      </ingredientes>
    </sopa>
    
    <sopa nombre="Mariana" precio="20€">
      <ingredientes>
        <ingrediente>Berengenas</ingrediente>
        <ingrediente>Apio</ingrediente>
        <ingrediente>Queso</ingrediente>
      </ingredientes>
    </sopa>

    <sopa nombre="Coralna" precio="18€">
      <ingredientes>
        <ingrediente>Apio</ingrediente>
        <ingrediente>Puerros</ingrediente>
        <ingrediente>Huevo</ingrediente>
      </ingredientes>
    </sopa>
  </sopas>

  <postres>
    <titulo precio="4€">Tiramisú</titulo>
    <titulo precio="2€"> Fruta</titulo>
  </postres>
</cocina>
