=== pan-narrans/DAW/Marcas/XML/Práctica Exámen/test.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="impair" type="xs:string " />
  <xs:element name="pair" type="xs:string " />

  <xs:element name="livre">
    <xs:complexType>
      <xs:sequence>
        
        <xs:sequence minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="impair" />
          <xs:element ref="pair" />
        </xs:sequence>
        
        <xs:element ref="impair" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== pan-narrans/DAW/Marcas/XML/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<livre xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test.xsd">

  <secuencias>
    <impair>qwe</impair>
    <pair>qwe</pair>
    <impair>qwe</impair>
    <pair>qwe</pair>
    <impair>qwe</impair>
    <pair>qwe</pair>
    <impair>qwe</impair>
    <pair>qwe</pair>
    <impair>qwe</impair>
    <pair>qwe</pair>
    <impair>qwe</impair>
    <pair>qwe</pair>
  </secuencias>

  <impair>qwe</impair>

</livre>
